### PR TITLE
Enable jest coverage

### PR DESCRIPTION
**Pull request by abetomo**
# Pull Request

## Problem

-

## Solution

The coverage of the test will now be displayed.

```
----------|---------|----------|---------|---------|--------------------------------------------------------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|--------------------------------------------------------------------
All files |   88.02 |    83.86 |   92.31 |   88.21 |
 index.js |   88.02 |    83.86 |   92.31 |   88.21 | ...328,1465-1466,1480-1481,1524,1568-1583,1589,1637,1754,1850-1880
----------|---------|----------|---------|---------|--------------------------------------------------------------------
```

### CODE REVIEW

**Comment by shadowspawn** [comment]
I have checked sometimes by running manually with `npm jest --coverage`, but happy to have it on by default. Not aiming for 100% though. 😄 Will add one suggestion in review.

**Review by shadowspawn — CHANGES_REQUESTED** [review]
I recommend add `coverage` folder to `.gitignore`.

**Comment by abetomo** [comment]
Sure!
'coverage' has been added to gitignore.
Thank you!

**Review by shadowspawn — APPROVED** [review]
LGTM

**Pull request merged**
