### PR TITLE
Feature/http client

### PR DESCRIPTION
**Pull request by aemonge**
# Pull Request

## Problem
Enhancement, allow the commander utility to serve as an http server version of the CLI. 

## Solution
By passing to the program main class an Express server variable, it's been able to be used as a web-client software. Allowing a easy deployement of a CLI or WebInterface tooling.

```
const express = require("express");
const app = express();
// ....................
app.use(express.json());
program.parse(app, {from: "express", port: 8080});
```
## Discussion

Documentation should be change to include the new feature, and also to recommend the usage of the `program.write` function to centralize the communication that can be either a `express.send` or a `console.log`.

Moreover this pull-request needs to be updates to include the unit testing of my new functions, to guarantee they wont break in the future

### Added
 - Added http client support, to use the create tool not only as CLI but also as a web client.

### CODE REVIEW

**Comment by shadowspawn** [comment]
This is probably too special-case for Commander core.

I don't really understand the use case. Why parse command-line style commands through a web interface?

I suspect there are some runtime issues:
1) By default, Commander will exit the process if the parsing fails (taking down your server)
2) Commander does not clear out state when doing a parse. You need to create a new Command to do another parse.

**Comment by shadowspawn** [comment]
Related: #351 #1335

**Comment by aemonge** [comment]
Hi, 

Indeed, I've found that both things are needed to be considered. Since the state wont be cleared, I thought of closing the connection after processing successfully or not any command. This way it will behave more as the CLI it is, and only delegating the input/output to a HTTP channel. And to use a `while` bash loop, or a `forever` script to keep it alive; sidestepping away from the issues we're both aware.

Also, I do agree with you in the sense that this is out of scope of the main Commander core; maybe we can work together to enable Commander to support a plug-in system in which this feature can be the first plug-in. 

To be honest, I think the only purpose to enable a webHttp I/O for the scripts is to share to none-cli programmers. In my strict case, my colleagues are afraid of opening a terminal (such a shame, i know....) but they aren't afraid of using an API.  So that's the main goal of it, to allow an easy portability of a CLI script.

**Comment by shadowspawn** [comment]
Thanks for the usage comments.

I think it would be easier to have a web server call Commander, than Commander "be" a web server. `.exitOverride()` both modifies the default exit-on-error behaviour, and includes the error string in the exception, which might allow convenient passing back over the http channel.

No plugin plans currently.

Closing this as out of scope for Commander.

**Comment by aemonge** [comment]
Ok..... just let me know if I can help in the future if you ever decide to implement plugins.

**Comment by aemonge** [comment]
By the way, I'm using [pm2](https://pm2.keymetrics.io/) to restart the script after any process, so now it can be keep alive for every for DeamonHttp purposes

**Pull request closed without merging**
