### PR TITLE
Update CHANGELOG for 13.0.0

### PR DESCRIPTION
**Pull request by shadowspawn**
Add last PR to CHANGELOG. Have not bumped version number.

I think 13.x is ready for release. I am not planning to do another prerelease.

This can go out when suits you @abetomo, no hurry. I put in today's date as a placeholder not an expectation. 😁  
(And if you are busy or on holiday, I am happy to do it.)

### CODE REVIEW

**Review by abetomo — APPROVED** [review]

**Comment by abetomo** [comment]
Sorry for the delay in replying.

**Comment by shadowspawn** [comment]
Branch `release/13.x` is ready for release. (Version number not set yet.)

**Comment by abetomo** [comment]
Thanks.
I have released it.

**Comment by shadowspawn** [comment]
Woop! Thanks @abetomo

**Pull request merged**
