### PR TITLE
update Readme_zh-CN to v3.0.0 and modify some old translation problems

### PR DESCRIPTION
**Pull request by oGsLP**
Keep pace with the latest official Readme.

### CODE REVIEW

**Comment by shadowspawn** [comment]
(The Travis CI Build looks like it failed with network problems not related to this PR.)

**Comment by oGsLP** [comment]
Emm..then what should I do?

**Comment by shadowspawn** [comment]
Sorry I was not clear, you do not need to do anything. Not your changes. We'll sort it out. :-)

**Comment by abetomo** [comment]
Passed by re-run.

**Comment by shadowspawn** [comment]
I will update master and develop branches tonight.

Thank you  for your contributions.

**Pull request merged**
