### PR TITLE
version bump 2.12.0

### PR DESCRIPTION
**Pull request by abetomo**

### CODE REVIEW

**Comment by abetomo** [comment]
@vanesyan Could you review it?

**Comment by vanesyan** [comment]
Aren't there any breaking changes?

**Comment by abetomo** [comment]
@vanesyan `Print default value in option help` may have a big impact.

**Comment by abetomo** [comment]
Since #704 has been merged, it closes.

**Comment by abetomo** [comment]
@vanesyan Please release at good timing.

**Pull request closed without merging**
