### PR TITLE
Feature/prettier

### PR DESCRIPTION
**Pull request by shadowspawn**
# Pull Request

## Problem

ESLint are deprecating the formatting rules, and suggest using a separate formatter.

Using StandardJS and TypeScript equivalent has been painful to maintain. (To be fair, partly because of how we ended up using it.)

See: #2104

## Solution

Use ESLint for linting. Start with ESLint recommended rules.

Use Prettier for formatting. In a way this is quite like using Standard, opinionated so less setup and debate over settings!

Note: I saw there was a new [flat config](https://eslint.org/blog/2022/08/new-config-system-part-2/) for ESLint and liked the look of it. Later I found it is in active development and plugins still working on adoption. Flat config is going to be default in ESLint 9. I used the new config file name `eslint.config.js` so detected as flat from command-line with ESLint 8, but currently in the VSCode editor also need to turn on the experimental flat config support in the eslint VSCode extension.

### CODE REVIEW

**Comment by shadowspawn** [comment]
There will be lots of minor formatting churn. As expected! I have just played with a few files so far, not committed.

```console
% npx prettier --check .

Checking formatting...
[warn] esm.mjs
[warn] examples/action-this.js
...
[warn] tests/ts-imports.test.ts
[warn] typings/index.d.ts
[warn] typings/index.test-d.ts
[warn] Code style issues found in 127 files. Run Prettier to fix.
```

```diff
% npx prettier -w lib/option.js
lib/option.js 45ms
% git diff -U1                                                                                                          feature/prettier
diff --git a/lib/option.js b/lib/option.js
index f061901..30cddad 100644
--- a/lib/option.js
+++ b/lib/option.js
@@ -182,3 +182,5 @@ class Option {
       if (!this.argChoices.includes(arg)) {
-        throw new InvalidArgumentError(`Allowed choices are ${this.argChoices.join(', ')}.`);
+        throw new InvalidArgumentError(
+          `Allowed choices are ${this.argChoices.join(', ')}.`,
+        );
       }
@@ -257,3 +259,3 @@ class DualOptions {
     this.dualOptions = new Set();
-    options.forEach(option => {
+    options.forEach((option) => {
       if (option.negate) {
@@ -284,3 +286,3 @@ class DualOptions {
     const preset = this.negativeOptions.get(optionKey).presetArg;
-    const negativeValue = (preset !== undefined) ? preset : false;
+    const negativeValue = preset !== undefined ? preset : false;
     return option.negate === (negativeValue === value);
@@ -315,3 +317,4 @@ function splitOptionFlags(flags) {
   const flagParts = flags.split(/[ |,]+/);
-  if (flagParts.length > 1 && !/^[[<]/.test(flagParts[1])) shortFlag = flagParts.shift();
+  if (flagParts.length > 1 && !/^[[<]/.test(flagParts[1]))
+    shortFlag = flagParts.shift();
   longFlag = flagParts.shift();
```

**Comment by shadowspawn** [comment]
Can see the havoc on the branch with `npx prettier -w .` and looking at changes.

I did carefully hand-craft much example code that will change, but readers may find it easier to read with well known style rather than custom style anyway.

**Comment by shadowspawn** [comment]
I am interested in looking at:
- ESLint plugin `eslint-plugin-jsdoc`
- Prettier formatting for Markdown et al. I just turned on JavaScript and TypeScript file types initially.

**Comment by abetomo** [comment]
Oooh, release/12.x has been deleted and is now closed.
Do you prefer to merge to `develop`?

**Comment by shadowspawn** [comment]
No problem. I'll open a PR against develop branch.

**Pull request closed without merging**
