### PR TITLE
Suggestion for unknown command and unknown option

### PR DESCRIPTION
**Pull request by shadowspawn**
# Pull Request

## Problem

It is common for big utilities to suggest matches for command typos:

```
% git loe
git: 'loe' is not a git command. See 'git --help'.

The most similar commands are
	clone
	log

% npm publih

Usage: npm <command>

...short-help...

Did you mean one of these?
    publish
    unpublish

% hg loe
hg: unknown command 'loe'
(did you mean one of clone, locate, log?)
```

CLI parsing:

- https://yargs.js.org/docs/#api-reference-recommendcommands opt-in, single suggestion
- https://github.com/spf13/cobra/blob/master/user_guide.md#suggestions-when-unknown-command-happens opt-out

Resolves issue: #1015

Note. There have not been a lot of requests for this but I have been noticing it in programs I use. It is already possible for user to add their own suggestions for commands, and there has been interest in that:

- https://github.com/tj/commander.js/issues/660#issue-243400277
- #1176
- https://github.com/tj/commander.js/issues/432#issuecomment-175785162
- https://github.com/tj/commander.js/issues/1015#issuecomment-521103051

## Solution

1. Check for possible matches to add to the unknown-command error message. Take into account the visible command alias, the implicit help command, and ignore hidden commands. Use the Damerau–Levenshtein distance to calculate the edit distance, which tries insertion, deletion, substitution, and transposition.

```
% node index.js rat
error: unknown command 'rat'
(Did you mean cat?)
```

This does not affect users who already have their own `command:*` listener.

2. Check for possible matches to add to the unknown-option error message. (None of git or hg or npm do this.) Take into account global options, the implicit help option, and ignore hidden options.

```
% node index.js sub --debgu
error: unknown option '--debgu'
(Did you mean --debug?)
```

3. Offer multiple suggestions (if more than one at closest edit distance).

```sh
% node index.js fake
error: unknown command 'fake'
(Did you mean one of bake, make, rake?)
```

4. Make the suggestions off by default to minimise breakage in Commander 8, and probably switch to on by default in Commander 9.

## ChangeLog

- added: `.showSuggestionAfterError()` to show suggestions after unknown command or unknown option

And fixed a bug discovered when testing:

- changed: show error for unknown global option before subcommand (rather than just help)

### CODE REVIEW

**Review by abetomo — APPROVED** [review]
awesome!

**Comment by shadowspawn** [comment]
Thanks Abetomo. 👍

**Comment by shadowspawn** [comment]
Shipped in Commander v8.2.0

**Comment by nicojs** [comment]
Thanks for adding this feature. Easy to use and works like a charm. Brings a lot of value! 💚

**Pull request merged**
