### PR TITLE
Add hooks for life cycle events: using .hook()

### PR DESCRIPTION
**Pull request by shadowspawn**
# Pull Request

## Problem

People ask for a way to run code before the action handler with access to the parsed options. And also some requests for a hook after the action.

Main issue: #1197
Related issues: #76 #229 #936 #996 #1158 #1457

## Solution

Add `.hook(event, callback)` method
- supports async callbacks
- supports multiple hooks for same event on single command

Supported hooks: `preAction`, `postAction`. Triggered by action handler for hooked command and its subcommands.

Callback is passed the hooked command and the command running the action handler.

## ChangeLog

- add `.hook()` with support for `"preAction"` and `"postAction"` callbacks

### CODE REVIEW

**Comment by shadowspawn** [comment]
Wondering about changing signature to named method and parameters, say:

```js
program
   .preAction((thisCommand, actionCommand) => {});
   .postAction((thisCommand, actionCommand) => {});
```

**Comment by shadowspawn** [comment]
Why not preHandler or afterHandler to also cover executable? The stand-alone executable seems quite different, and I have been avoiding tackling! Initial concerns without deep digging:
- the command which is about to be "executed" is a dummy command
- the command object which is about to be executed does not currently have `.args` set
- the program gets terminated when the subprocess finishes (?), but could perhaps run afterHandler before exit? But what about async?

**Comment by shadowspawn** [comment]
As noted in https://github.com/tj/commander.js/pull/1519#issuecomment-841617643, the `.hook()` api signature is similar to that used by Fastify:

https://www.fastify.io/docs/latest/Hooks/

**Review by abetomo — APPROVED** [review]
LGTM

**Comment by shadowspawn** [comment]
Thanks @abetomo

I'll take another look at the code refactor next, and then focus on a prerelease of Commander v8.

**Pull request merged**
