### PR TITLE
Improve executable subcommand tracking

### PR DESCRIPTION
**Pull request by shadowspawn**
Improve executable subcommand tracking, and update dependencies. A last release for 3.x series?!

This can be released if you are happy with it @abetomo 

I'll update PR and release notes with credit details after release.

### CODE REVIEW

**Comment by shadowspawn** [comment]
Thanks. Merged. Will you publish?

**Comment by abetomo** [comment]
Thank you.
Released.

**Comment by shadowspawn** [comment]
Thanks to Checkmarx Application Security Research Team for reporting an issue.

**Comment by shadowspawn** [comment]
This issue was responsibly reported by the Checkmarx Application Security Research Team. It was fixed in  v2.20.3 (#1059) and v3.0.2(#1056).

The Checkmarx vulnerability library lists this as: https://devhub.checkmarx.com/cve-details/Cx435a6fda-ca38/

**Pull request merged**
