### PR TITLE
Automatically check for missing required options

### PR DESCRIPTION
**Pull request by marcelofarias**

### CODE REVIEW

**Comment by travisperson** [comment]
Why not have a `required` function, which acts the same as `option` but sets a flag?

**Comment by marcelofarias** [comment]
Isn't it what's already implied by <> like in "-r <required>"? I mean, does it make sense to mark an option as <required> and allow the user to not supply it at all?

**Comment by travisperson** [comment]
> I mean, does it make sense to mark an option as <required> and allow the user to not supply it at all?

I think so. The angel brackets say that if you use this flag, you must also provide a value. There might also be times when I want to force the user to provide an argument, but I wish to have it named.

So I can see two types of flag style arguments for required.

1) A flag that if specified, has a required value (angle brackets)
2) A flag that must be supplied (non optional flag)

**Comment by rottmann** [comment]
:+1: 
Or name the function `requiredOption` (no need to change or touch the option() args), so it is obvious that an option is required.

**Comment by snow01** [comment]
I have fixed this in different manner. No additional function or flag is required. See here - https://github.com/tj/commander.js/pull/503

**Comment by brunapereira** [comment]
@snow01 Your fix just makes sure that if I have a flag `-C` without a value, it will throw an error. I think the main idea of the functionality is throw an error when the flag itself is not specified.
Nowdays: `./command -C => throws an error`
What is being required: `./command => throws an error. Where is the flag -C?`

So, will the feature be merged? 😄

**Comment by nickbarry** [comment]
I agree something like this would be helpful. In the meantime, I wrote a utility function that automatically checks for required params:

```javascript
cli
  .version('0.0.1')
  .option('-y, --year <y>', 'Year for reports')
  .option('-d, --directory <path>', 'Directory with the report subdirectories')
  .option('-u, --upload', 'Do upload files for matched companies')
  .parse(process.argv);
assertRequiredArgs(cli);

function assertRequiredArgs(cli) {
  const ommittedRequiredParameters = [];
  cli.options.forEach((option) => {
    if (option.required && !cli.hasOwnProperty(name)) {
      const name = option.long.slice(2);
      ommittedRequiredParameters.push(name);
    }
  });

  if (ommittedRequiredParameters.length !== 0) {
    throw new Error(`The following required parameters were ommitted: ${ommittedRequiredParameters.join(', ')}`);
  }
}
```

**Comment by shadowspawn** [comment]
I think this Pull Request allows treating all options with required values as mandatory options that must be specified? I consider those two independent things, as noted by some of the other comments.

See https://github.com/tj/commander.js/issues/230#issuecomment-478181355 for a long description.


This Pull Request has not had any activity in over six months.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Pull request closed without merging**
