### PR TITLE
*: update dev deps and make tweaks

### PR DESCRIPTION
**Pull request by VoltrexKeyva**
- Update the developer dependencies to their latest versions.
- Remove usage of the `--experimental-modules` CLI flag as it's a no-op now.
- Make changes to some of the typings files to make the linters happy.

### CODE REVIEW

**Comment by shadowspawn** [comment]
Commander 9 supports node v12.20.0 and up, so can't upgrade to latest Jest on mainline yet as it requires node 14. The `release/10.x` branch has minimum of node 14 for the next major version.

**Comment by VoltrexKeyva** [comment]
I see, although I'm not sure what happened here while changing the target branch to `release/10.x`, this is weird.

**Comment by shadowspawn** [comment]
Yes, commits disappeared?!

I made some updates in #1826, but not including the `record` change suggested by (I assume) new version of eslint.

**Comment by VoltrexKeyva** [comment]
Hmm, I guess I'll just open another PR 😅

**Pull request closed without merging**
