### PR TITLE
Add ability to specify arguments syntax for top-level command

### PR DESCRIPTION
**Pull request by rrthomas**
* index.js: Add arguments method, support top-level command in action.

This would fix issue #257.

### CODE REVIEW

**Comment by goloroden** [comment]
Any chance that this will be merged in the near future?

**Comment by SomeKittens** [comment]
LGTM.  Sorry about the wait.

**Comment by rrthomas** [comment]
Thanks, @SomeKittens!

**Comment by goloroden** [comment]
Awesome, I really appreciate what you did here :-)

The only thing I am missing is an update to the docs: How do I use this?

**Comment by rrthomas** [comment]
@goloroden: for now, see #257. Please file a new issue for documentation, and I'll do it when I can.

**Comment by goloroden** [comment]
Okay :-)

**Comment by zhiyelee** [comment]
@thethomaseffect @rrthomas IMO, It would be better that  PRs like this  should get merged after the document is ready.

I am preparing  for the next release and find this PR without document.

**Comment by rrthomas** [comment]
@zhiyelee see PR #392.

**Pull request merged**
