### PR TITLE
Use fork for explicit js.

### PR DESCRIPTION
**Pull request by vilic**
It's somewhat a "feature" request, as I am trying to get https://github.com/jaredallard/nexe working with commander.js.

Please let me know if there's any concern, thanks!

### CODE REVIEW

**Comment by GM-Alex** [comment]
Please merge that change, the possibility to use commander with nexe would be awesome.

**Comment by yasserf** [comment]
+1

**Comment by vanesyan** [comment]
Is it active yet? There is still integration test failures

**Comment by vilic** [comment]
@vanesyan The last two commits is not actually part of this PR, but I am closing it anyway.

**Comment by vanesyan** [comment]
Okay, feel free to open another one if necessary

**Pull request closed without merging**
