### PR TITLE
chore: Included githubactions in the dependabot config

### PR DESCRIPTION
**Pull request by naveensrinivasan**
This should help with keeping the GitHub actions updated on new releases. This will also help with keeping it secure.

Dependabot helps in keeping the supply chain secure https://docs.github.com/en/code-security/dependabot

GitHub actions up to date https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by shadowspawn** [comment]
Oh, just for github-actions. I don't monitor those, and don't expect huge noise, unlike the npm dev dependencies.

Yes from me.

**Review by shadowspawn — APPROVED** [review]

**Comment by naveensrinivasan** [comment]
> Oh, just for github-actions. I don't monitor those, and don't expect huge noise, unlike the npm dev dependencies.
> 
> Yes from me.

@shadowspawn  Thanks, Is there anything else you need from me to merge this?

**Comment by shadowspawn** [comment]
Nothing from you @naveensrinivasan thanks. 

Both maintainers review PR before landing the commits on the develop branch.

We copy up to master and release every month or so.

**Review by abetomo — APPROVED** [review]
Thanks!
Sorry I'm late.

**Pull request merged**
