### PR TITLE
Watch for npm package updates with dependabot

### PR DESCRIPTION
**Pull request by abetomo**
# Pull Request

## Solution

How about checking npm package update in dependabot?

### CODE REVIEW

**Comment by shadowspawn** [comment]
I find it noisy in repos that aren't actively maintained, but have never tried it. Happy to give it a go. Dependency maintenance is considered a best practice these days.

**Review by shadowspawn — APPROVED** [review]

**Comment by abetomo** [comment]
Thanks for the review!

**Comment by shadowspawn** [comment]
I think the recent merges have included all the PR commits. I suggest doing a "Squash and merge" normally. I think the single commit for the PR is more useful when researching code history than hitting wee commits from during the PR development. I don't feel too strongly about it and if there is a reason to normally pick a different merge type then let me know!

I think Github just leaves the last selected merge type as the default for the next one, so easy to miss.

(I just picked one of the recent PRs to make a comment on. This PR only had two commits anyway.)

**Comment by abetomo** [comment]
I got it.
I'll do that next time.

**Pull request merged**
