### PR TITLE
Add support for exit codes.  

### LINKED ISSUE #188: optional exit value for Help. (feature request)
It would be extremely convenient for help to take an optional return value so that the program could easily exit with an error code. This is useful in cases where a combination of options are required together and you would want to report to the user the usage but also to the system not to continue with anything else that may be in the execution chain.

### LINKED ISSUE #435: process.exit(64)
When you call exit, the return code probably should not be `0` (success).  Traditionally, option parsing errors have resulted in error code 64, as documented in many systems' `sysexits.h` header file, which on my system says:

```
#define EX_USAGE    64  /* command line usage error */
```

I would be happy to submit a PR if you're open to this change.

### PR DESCRIPTION
**Pull request by hildjj**
Fixes #435.  
Fixes #188.

### CODE REVIEW

**Comment by SomeKittens** [comment]
Broken tests, can you fix those up?

**Comment by zhiyelee** [comment]
@SomeKittens  I'm not sure whether we need that

**Comment by zhiyelee** [comment]
Also that would be break change to change default code from 1 to 64.

**Comment by hildjj** [comment]
Sorry, thought I had gotten all of the tests fixed up.  I think there's a legitimate discussion to be had about what exit code to use when the user *asks* for help with `--help` vs. when they supply invalid arguments.  I would be fine with `--help` returning 0, if you prefer.

**Comment by hildjj** [comment]
Oh, and I'm also happy to change the defaults so that the interface doesn't change, and only the people that want 64-exits get them.

**Comment by zhiyelee** [comment]
@hildjj Thank you!  I'm not sure `64` is convention for such error. I have checked `wget` and `git` with unknown option, they give `2` and `129` respectively. 

I am open to allow user set custom exit code.

**Comment by SomeKittens** [comment]
@zhiyelee good checking - I'm ok with user-set as well.

**Comment by vanesyan** [comment]
@zhiyelee is it still necessary?

**Comment by shadowspawn** [comment]
I have added this pull request to a triage collection of related issues for future reference.

This pull request has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Pull request closed without merging**
