### PR TITLE
Fix translation errors.

### PR DESCRIPTION
**Pull request by HakurouKen**

### CODE REVIEW

**Comment by abetomo** [comment]
@HakurouKen Would you please resolve the conflict?

**Comment by HakurouKen** [comment]
Sure, resolved.

**Comment by abetomo** [comment]
Thank you!
I can not strictly check this language because I do not understand this language.
I will merge, but if you notice something, please give me a PR again.

**Comment by zhiyelee** [comment]
thanks @abetomo

**Pull request merged**
