### PR TITLE
Feature/prepare for 7

### PR DESCRIPTION
**Pull request by shadowspawn**
# Pull Request

Update CHANGELOG, version, and date ready for 7.0.0

### CODE REVIEW

**Review by abetomo — APPROVED** [review]
7️⃣ 🎉

**Comment by shadowspawn** [comment]
Ready to go out on Friday.

**Comment by shadowspawn** [comment]
Ready for you to release @abetomo (or I can do it if you prefer).

**Comment by abetomo** [comment]
v7.0.0 has been released.
Thanks!

**Comment by shadowspawn** [comment]
Woop woop! 🎉

**Pull request merged**
