### PR TITLE
Prepare for 6.1.0

### PR DESCRIPTION
**Pull request by shadowspawn**
# Pull Request

Prepare for v6.1.0 release.

- set version number
- update CHANGELOG

### CODE REVIEW

**Comment by shadowspawn** [comment]
```
% npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 817 scanned packages
```

**Review by abetomo — APPROVED** [review]
✅

**Comment by abetomo** [comment]
Thank you. We have released it.

**Comment by shadowspawn** [comment]
Thanks @abetomo 🎉 

(I'll tidy up the related issues and labels over weekend.)

**Pull request merged**
