### PR TITLE
Release/12.x

### PR DESCRIPTION
**Pull request by abetomo**
bump to 12.0.0

### CODE REVIEW

**Comment by abetomo** [comment]
`This branch cannot be rebased due to conflicts`
Cannot rebase merge to `develop`.

**Comment by shadowspawn** [comment]
I had already merged from develop to release/12.x, and a rebase would be complicated. But a plain merge is fine and no conflicts.

**Comment by abetomo** [comment]
Thanks!

**Comment by abetomo** [comment]
Released.

**Comment by shadowspawn** [comment]
Woop!

**Pull request merged**
