### PR TITLE
fix: Add node types to typings

### PR DESCRIPTION
**Pull request by ffflorian**

### CODE REVIEW

**Comment by shadowspawn** [comment]
@ffflorian What problem is this Pull Request solving?

**Comment by ffflorian** [comment]
@shadowspan
commander's typings use interfaces from Node so the reference should be included. When I wanted to create typings for commander-remaining-args (see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36148) I needed to reference Node's typings explicitly. This could've been avoided by just referencing them here.

**Comment by shadowspawn** [comment]
Related link:
- https://github.com/tj/commander.js/pull/646#issuecomment-347374100

**Comment by ffflorian** [comment]
@shadowspawn 

From the comment:

> You can include the `/// <reference types="node">` flag to access `EventEmitter` and anything else needed

Does that mean you approve?

**Comment by shadowspawn** [comment]
No it does not mean I approve, it means I have started looking into it. If you have good links for the details of what `reference types` does, I'll be reading up on that too. (I review Pull Requests fairly carefully and add more comments than you might expect.)

**Comment by ffflorian** [comment]
> I review Pull Requests fairly carefully and add more comments than you might expect.

You don't know what I expect :slightly_smiling_face: I was just wondering what you meant by your comment, sorry. Take your time!

Here are the docs for `reference types`: https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html

In short: 

> Triple-slash references instruct the compiler to include additional files in the compilation process.

**Comment by ffflorian** [comment]
@shadowspawn I removed the changes to the contributors line.

**Comment by shadowspawn** [comment]
Thanks @ffflorian

**Comment by shadowspawn** [comment]
Merging into `release/3.0.0` branch

**Comment by shadowspawn** [comment]
Already had two approvals. Merged into v3 and will be included in that release. Closing to make it clear that should not be merged into master.

Thank you for your contributions.

**Comment by ffflorian** [comment]
Thanks @shadowspawn @abetomo, looking forward to v3!

**Comment by shadowspawn** [comment]
Available now as a prerelease. See #1001

**Comment by shadowspawn** [comment]
Shipped in v3: https://github.com/tj/commander.js/releases/tag/v3.0.0

**Pull request closed without merging**
