### PR TITLE
added optional callback to help functions

### PR DESCRIPTION
**Pull request by djulien**
Added an optional callback to the help functions to allow post-processing of help text before it is displayed.

### CODE REVIEW

**Comment by SomeKittens** [comment]
Change looks good, can you not update the version in package.json just yet?

**Comment by djulien** [comment]
Sorry - I thought any change to behavior was supposed to have a version# change as well.
Should I just commit a new change on top of it to put it back?  (I don't know all the fancy branching and merging git procedures, just the basics)

**Comment by SomeKittens** [comment]
you're totally correct about versioning, just that it's up to the project maintainers to cut a release.  If you can, squash your changes down to one commit.  (good time to learn about `git reset`)

**Comment by djulien** [comment]
I looked up reset but wasn't comfortable with the head#.  I also found something called "interactive rebase" which sounded like it would allow me to just drop the version# part of the changes, so I gave that a try.  Does the commit look okay now, or do I still need to merge it all into one?

**Comment by SomeKittens** [comment]
Ah, I'll just squash 'em.

**Comment by SomeKittens** [comment]
Alright, all squished and joined in 4d421f9fd263b4035497893ab87fd111c4f3464f

Thanks!

**Pull request closed without merging**
