### PR TITLE
resolves #741 make indentation configurable

### LINKED ISSUE #741: Make help indentation configurable
commander.js indents all lines in the help output. This is atypical. I don't know many commands that output help with this formatting (if you consider node, npm, lerna, ruby, docker, git, grep, find, vim, rpm). I'd like to make my command look more like the typical command. Please make the indentation size configurable, or provide a switch to disable it outright.

Commands which do use indentation include yarn and gem. Yarn happens to have indentation because it's using this package ;)

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
I'm still playing with this one a bit. And I need to add a test.

**Comment by mojavelinux** [comment]
Okay, that should give us something to discuss.

Here's what I'm thinking. First, we may want to use numbers instead of strings for indent and spacing. For example, INDENT=2, SPACING=1 (which are the defaults). That will require some rework.

I'm also thinking that perhaps this logic should be moved to the functions `space()` and `indent()`. That's pretty simple for everything except `helpInformation` which requires adding a few extra lines to keep the sections from crashing into each other.

**Comment by vanesyan** [comment]
Generally this is good idea. Yes, I like the second form of control indentation (through numbers) more that the first one.

**Comment by shadowspawn** [comment]
Related issue was closed and OP happy with subsequent improvements: https://github.com/tj/commander.js/issues/741#issuecomment-452632316

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by mojavelinux** [comment]
Agreed. I think we came to a different agreement to solve the same problem.

**Pull request closed without merging**
