### PR TITLE
Add document links to errors

### PR DESCRIPTION
**Pull request by abetomo**
# Pull Request

## Problem

Not that there was a problem.

## Solution

I saw another tool that included the URL of the document in the error message.
That helped to solve the problem.

It's just one idea, so close it if you don't need it.

### CODE REVIEW

**Comment by shadowspawn** [comment]
Short version: 👍 

-----

Long version

The small concern I have is building a link to a particular section in the README is fragile in the longterm because the README may change. It doesn't completely break though, just loads at top of page.

We are trying hard in the throw to help the person solve the problem, and adding an URL may help them.

(If we need to offer more specific help for a throw case we could add a separate page to link to, but hopefully we are offering enough!)

**Comment by shadowspawn** [comment]
I'll try it out before I finish reviewing it. Because the message appears in the middle of a throw with stack etc, I had tried to pull together the additional lines so they didn't get lost in the noise starting the lines with dash. Not sure how effective it is, so I'll try generating a throw with new link to see how it looks!

**Comment by abetomo** [comment]
Thank you for the review!

**Comment by shadowspawn** [comment]
Released in Commander v6.1
https://github.com/tj/commander.js/releases/tag/v6.1.0

**Pull request merged**
