### PR TITLE
doc: typo in command example

### PR DESCRIPTION
**Pull request by bodinsamuel**
- Correct a small typo in `command()` example

### CODE REVIEW

**Comment by bodinsamuel** [comment]
Not sure why it failed, seems unrelated 🙇

**Comment by shadowspawn** [comment]
Would you please edit your Pull Request and change the target branch to `develop`? Should be easy, don't go to trouble of making a new pull request if you don't see how to do it!

Normally I would accept a documentation fix directly on master, but hopefully on the develop branch we have fixed the false-positive test failures with ts-node which you hit, so I am interested to check the tests pass on develop.

Thanks for the correction.

**Comment by bodinsamuel** [comment]
done 👌

**Comment by shadowspawn** [comment]
Thank you  for your contributions.

**Pull request merged**
