### PR TITLE
ESLint changes preparing for Prettier

### PR DESCRIPTION
**Pull request by shadowspawn**
# Pull Request

## Problem

ESLint have deprecating the formatting rules, and suggest using a separate formatter.

Using StandardJS and TypeScript equivalent has been painful to maintain. (To be fair, partly because of how we ended up using it.)

See: #2104

## Solution

Use ESLint for linting. Start with ESLint recommended rules.

Use Prettier for formatting. In a way this is quite like using Standard, opinionated so less setup and debate over settings! Installed and configured in this PR, but not used to format files yet to keep the PR focused on the setup changes.

I did a rework of the naming of the npm scripts so now `check` lint/format/type, and `fix` lint/format.

Note: I saw there was a new [flat config](https://eslint.org/blog/2022/08/new-config-system-part-2/) for ESLint and liked the look of it. Flat config is going to be default in ESLint 9. I used the new config file name `eslint.config.js` so detected as flat from command-line with ESLint 8.

Note: `eslint-plugin-jsdoc` installed but not activated yet, as will complain about multiple issues. Have also installed `prettier-plugin-jsdoc` which will hopefully fix some of the lint issues! Will evaluate those in separate PR.

For interest, I found a good blog after doing most of the work: https://www.joshuakgoldberg.com/blog/configuring-eslint-prettier-and-typescript-together/

### CODE REVIEW

**Comment by shadowspawn** [comment]
`typescript-eslint` has been updated for flat config since I started looking at this, and PR is updated.

Jest config is working fine with the old config unpacked, but they are working on explicit flat config support so waiting for that to land: https://github.com/jest-community/eslint-plugin-jest/issues/1408

Support for `jsdoc` in both eslint and Prettier is in place but not active yet for eslint. Quite a few changes which I'll do in a separate PR.

**Comment by shadowspawn** [comment]
The Jest plugin has been updated with flat config support, so all the pieces are in place.

I could make a separate branch so we run Prettier on all the files too before we decide to merge to develop?

**Comment by shadowspawn** [comment]
When I tried upgrading eslint to v9, I hit some dependency conflicts. Moved back to draft while I investigate.

**Comment by shadowspawn** [comment]
Oh, eslint v9 is not released yet! That explains some of my problems. 🙊 Marking as ready for review again as up to date with current releases and using flat config.

**Comment by shadowspawn** [comment]
`eslint` allows custom js/ts processing in the config file, unlike `tsc`. So don't need separate run-scripts for javascript and typescript. Nice.

**Comment by shadowspawn** [comment]
This comment not directly related to this PR, but reminded by adding Prettier configuration for `jsonc` to allow comments.

TypeScript allows comments in the `tsconfig.json` configuration file(s), although that is not standard JSON and not even mentioned on the [tsconfig overview page](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html).

I have added quite a few comments, and it is helpful! It isn't causing any problems that I am aware of, and the files are clearly intended for TypeScript, so I am not planning to remove the comments unless problems come up.

**Comment by shadowspawn** [comment]
VSCode eslint extension now support flat config without needing to opt-in.

**Comment by shadowspawn** [comment]
VSCode eslint extension currently has an opt-in setting to support flat config: `Eslint › Experimental: Use Flat Config`

However, auto-detection is in development with an alpha yesterday:
- https://github.com/microsoft/vscode-eslint/issues/1644#issuecomment-1983423379

**Comment by shadowspawn** [comment]
The VSCode ESLint extension has flat config support by default available as a prerelease (can just switch to/from prerelease in extensions UX): https://github.com/microsoft/vscode-eslint/issues/1644#issuecomment-2031582679

**Review by abetomo — APPROVED** [review]
Awesome!

**Pull request merged**
