### PR TITLE
version bump 2.10.0

### PR DESCRIPTION
**Pull request by abetomo**

### CODE REVIEW

**Comment by vanesyan** [comment]
Lgtm, but @zhiyelee should review it, as a bunch of commits been accepted by him

**Comment by abetomo** [comment]
@vanesyan 
I am one of them, but I am in trouble with the 2.9.0 bug.
May I release 2.10.0?
(It has not been released for a long time.)

**Comment by vanesyan** [comment]
It's seems okay. Let's merge it.

**Comment by vanesyan** [comment]
Can you please release npm tag, as I'm afk

**Comment by abetomo** [comment]
Released

**Comment by vanesyan** [comment]
Good

**Pull request merged**
