### PR TITLE
Prepare for 9.2.0

### PR DESCRIPTION
**Pull request by shadowspawn**
Update CHANGELOG and version for v9.2.0.
Release late this week, if suits you @abetomo .

### CODE REVIEW

**Review by abetomo — APPROVED** [review]
👍

**Comment by shadowspawn** [comment]
The GitHub release pages is up and code tagged thanks, but no publish visible yet on npmjs.com. Maybe delayed. Have you published?

**Comment by abetomo** [comment]
Oooh, I just published it to npm.

**Comment by shadowspawn** [comment]
Sweet, thanks. 😄

**Pull request merged**
