### PR TITLE
update chinese readme 

### PR DESCRIPTION
**Pull request by wwwenjie**
update chinese readme to v9, slove #1660

### CODE REVIEW

**Comment by wwwenjie** [comment]
Sorry I didn't squash commits, we can squash it when merge

**Comment by shadowspawn** [comment]
In this repo we just squash commits when we merge, no need for you to do that for the Merge Request. Thanks.

**Review by shadowspawn — APPROVED** [review]
Looks good. Thanks for catching up with the pending changes only just committed too!

**Review by abetomo — APPROVED** [review]
Thanks!

**Pull request merged**
