### PR TITLE
8.0.0

### PR DESCRIPTION
**Pull request by shadowspawn**
Ready for release! 🎉 🎱 

Opening a PR so visible (although no need to use GitHub for merge).

Tentative release date Friday 25 June. 

(Reminder when merging release changes: don't squash the commits.)

### CODE REVIEW

**Comment by shadowspawn** [comment]
Hmm, we have not had a volunteer yet for updating Chinese translations (#1533). 
I'll open a PR with a note on affected pages that they currently describe Commander v7.

**Comment by abetomo** [comment]
Do you want to merge this branch into master?
スクリーンショット 2021-06-24 8 14 22

**Comment by shadowspawn** [comment]
We will want to update `master` branch when doing release, but merge does not need to be done using this PR.

I opened this PR for something visible for the v8 release, so it is targeting `master`. Do not need to actually do this PR though! It is fine do merge another way (like command-line) and just close this PR. 

FYI: `develop` and `release/8.x` branches currently have the same code, I have been keeping them in sync for the last couple of weeks.

**Comment by abetomo** [comment]
I see now. Got it, thanks!

**Comment by shadowspawn** [comment]
You can release when suits you  @abetomo (no rush). I can do it if you are busy.

**Comment by abetomo** [comment]
v8 has been released! 🚀

**Comment by shadowspawn** [comment]
Woop woop! Thanks @abetomo

**Pull request merged**
