### PR TITLE
#540 fix with sync write in stdout

### PR DESCRIPTION
**Pull request by tyge68**
@tj that should help to resolve the issue #540 can you please confirm and release it ? that would be really helpful.

### CODE REVIEW

**Comment by tyge68** [comment]
@tj forget it I was still running with 6.2.0 on mac os, updating to 6.6.0 resolved the issue #540 as it was suggested (6.2.1  contained the fixed I supposed). So I will close this one.

**Comment by tmarciszewski** [comment]
Is there a chance to introduce this change for previous versions of Node?

**Comment by tyge68** [comment]
Sure it can be used for older version of Node. Do you want me to reopen the
pull request ?

**Comment by tmarciszewski** [comment]
I'm not sure what's commander's approach to supporting older versions of node. I was wondering if it should be merged for older versions of node to work without problems.
Our project will probably upgrade from 6.0.0 to 6.6.0 in short time so it's not critically important for us, but others could run into this problem.

**Comment by zhiyelee** [comment]
Could you also edit the travis.yml and run the tests?

**Comment by tyge68** [comment]
The test will not help because it does write in the stdout and directly
exit. So it would exit the test as well abruptly. It can only work with a
manual test from what I could see.

**Comment by tyge68** [comment]
Actually a test is possible , it would be simply about creating a command with many options so that the result help text is large enough to fill the the buffer (expecially on Mac OS this happens quickly). Then the test would run that command as an external process (child_process), and read the output of that external process, then compare it to expected value, similar to the tests already existing.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Pull request closed without merging**
