### PR TITLE
Created new OptionConfig class (child of Option) to include config ob…

### PR DESCRIPTION
**Pull request by the-unfactoring-guru**
# Pull Request

## Problem
Adding a new form of creating an option object. This is to simplify work when creating multiple options

## Solution
Create an OptionConfig class that extends Option class, the only difference is that this new class recieves a config object with necessary fields.

Since TS and JS are really peeky with multiple constructors in one class, I chose this option.

`index.d.ts`
```typescript
//...
 export class OptionConfig extends Option{
    constructor(config: {flags: string; description?: string});
}
//...
```

`option.js`
```javascript
class OptionConfig extends Option {
  /**
   * Initialize a new `Option` with the given `config` object
   *
   * @param {{flags: string; description?: string}} config
   */
  constructor(config) {
    super(config.flags, config.description);
  }
}
```

### CODE REVIEW

**Comment by the-unfactoring-guru** [comment]
References and improves on #1642

**Comment by shadowspawn** [comment]
Related: #665 #1359

**Comment by shadowspawn** [comment]
> Adding a new form of creating an option object. This is to simplify work when creating multiple options

I am not sure I understand the problem you have in mind. Can you give an example of how OptionConfig will make it easier to create multiple options?

**Comment by shadowspawn** [comment]
I think a factory function might be a more appropriate approach than a subclass for the implementation.  e.g.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from

For a fuller implementation, issues have mentioned short and long, and an alternative approach to setup to avoid the difference between `<required>` and `[optional]`.

As it is, this PR can easily be added in client code.

**Pull request closed without merging**
