### PR TITLE
chore: Fix typo

### PR DESCRIPTION
**Pull request by jamesgeorge007**
fixed a minor typo.

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
cc @shadowspawn

**Comment by shadowspawn** [comment]
Thanks. Would you please edit your Pull Request to target the develop branch, rather than the master branch.

Not very necessary for a typo I know! But we have recently changed our workflow to bring PR in on develop, and I want to start using the workflow.

The branch is mentioned in [CONTRIBUTING](https://github.com/tj/commander.js/blob/master/.github/CONTRIBUTING.md) but if people don't see that, we might need to add it to a PR template too.

**Comment by jamesgeorge007** [comment]
cc @shadowspawn

**Comment by shadowspawn** [comment]
(Likely to be a month before we do our next release and this lands on master.)

Thank you  for your contributions.

**Comment by jamesgeorge007** [comment]
@shadowspawn would love to know your thoughts on [Mevn-CLI](https://github.com/madlabsinc/mevn-cli) & [teachcode](https://github.com/madlabsinc/teachcode). It would be great if you could give it a try and consider leaving a :star:

**Pull request merged**
