### PR TITLE
Update Chinese translations

### LINKED ISSUE #1533: Update Chinese README for 8.0
A PR to update the Chinese version of README is welcome.

README commits on release/8.x:
https://github.com/tj/commander.js/commits/release/8.x/Readme.md

Compare between master and release/8.x:
https://github.com/tj/commander.js/compare/master...release/8.x

### PR DESCRIPTION
**Pull request by wangweixuan**
Fixes #1533.

Based on [this diff `ff301fa...80054ba`](https://github.com/tj/commander.js/compare/ff301fa...80054ba#diff-1550ec65ac92f65817fc28928dfef526912b5f52356ff43651369bae92f56031).

My editor was configured to trim trailing spaces, and that results in a lot of changes. Hope you won't mind.

### CODE REVIEW

**Comment by shadowspawn** [comment]
Great, thanks @wangweixuan 
I'll have a look through.

**Review by shadowspawn — APPROVED** [review]
LGTM

**Review by abetomo — APPROVED** [review]
Thanks!

**Comment by shadowspawn** [comment]
Released in Commander v8.1

**Pull request merged**
