### PR TITLE
Version bump 2.20.3

### PR DESCRIPTION
**Pull request by abetomo**
# Pull Request

## Problem

https://github.com/tj/commander.js/pull/1074#issuecomment-540897417

## Solution

Bump 2.20.3.

### CODE REVIEW

**Comment by abetomo** [comment]
@shadowspawn I'm sorry many times. Could you review it?

**Comment by abetomo** [comment]
memo:

```
% npm publish --tag 2_x
```

**Comment by abetomo** [comment]
Thank you!

**Comment by abetomo** [comment]
2.20.3 has been released.

**Comment by shadowspawn** [comment]
Release notes and tags look good to me. Thanks @abetomo 👍

**Pull request merged**
