### PR TITLE
Feature/update chinese readme

### LINKED ISSUE #1420: Update Chinese README for 7.0
A PR to update the Chinese version of README is welcome.

README commits on `release/7.x`:
https://github.com/tj/commander.js/commits/release/7.x/Readme.md

Compare between `master` and `release/7.x`:
https://github.com/tj/commander.js/compare/master...release/7.x

Quite a few changes to the README with some rearrangements, some additions, and catching up with latest code patterns.

There is some new additional documentation in the `docs` folder, but I think those files are less important than the README:
https://github.com/tj/commander.js/tree/release/7.x/docs

### PR DESCRIPTION
**Pull request by CoderYihaoWang**
# Pull Request - Update Chinese Documents

- Update Chinese README to match release/7.x
- Add Chinese translation to documents in the `docs` folder, link to those from Chinese README
- Update for making excess args opt-in (#1429)

Closes #1420

### CODE REVIEW

**Review by abetomo — APPROVED** [review]
👍

**Review by shadowspawn — APPROVED** [review]
LGTM

**Comment by shadowspawn** [comment]
Thanks @CoderYihaoWang 👍

**Comment by shadowspawn** [comment]
Are you ok with me merging `release/7.x` branch onto `develop` now @abetomo ?

I think we are pretty close to release. I'll do another read through release notes first. Does next weekend (16-17 January) suit you? Could be sooner or later if you prefer! 😄

**Comment by abetomo** [comment]
Thanks! That’s fine.

**Pull request merged**
