### PR TITLE
Prepare for 7.1.0

### PR DESCRIPTION
**Pull request by shadowspawn**
# Pull Request

No rush. Preparing 7.1.0 for release when suits.

### CODE REVIEW

**Review by abetomo — APPROVED** [review]
👍

**Comment by shadowspawn** [comment]
Please release when convenient @abetomo , or let me know if you would like me to do this one. No rush.

**Comment by abetomo** [comment]
v7.1.0 has been released.
Thanks for all the support.

**Comment by shadowspawn** [comment]
Thanks @abetomo 🎉

**Pull request merged**
