### PR TITLE
Write help text to stderr instead of stdout

### PR DESCRIPTION
**Pull request by cengizhanbasak**
# Pull Request

https://github.com/tj/commander.js/issues/997

## Problem

Informative functions were writing to stdout, causing problems in piping the output of the script.

## Solution

Changed writing stdout to stderr.

## ChangeLog

- Changed stdout to stderr for informative outputs.

### CODE REVIEW

**Comment by shadowspawn** [comment]
There is a typo!

But changing over to `stderr` properly will require more work than this. When the help is explicitly asked for, the display should continue to go to stdout as now. It is only when the help is displayed due to an input error that it should go to stderr.

**Comment by cengizhanbasak** [comment]
Added a parameter for outputHelp, allowing users to specify if they want to output to stderr or not. Output is to stderr as default, "--help" outputs to stdout though.

**Comment by shadowspawn** [comment]
The failing test is due to one change you made which I think is not correct. I'll let you look into it. 

Note 1: you can run the tests locally before you push.
Note 2: there have been *big* changes to the tests on the develop branch, which has the code for the next version of Commander.

I do not want to change the public interface for `.outputHelp`, but that is a reasonable place to experiment as it is a bottleneck for the current calls. You have added a parameter to `.outputHelp`, but everywhere it is called you are passing `false` so I don't think you have changed the error case.

I think getting the help-as-error to stderr in a tidy way is a tricky problem and harder than it looks. If you find the associated `emit` call, you will see a further complication...

**Comment by shadowspawn** [comment]
I added a question for original poster. I was thinking about the help-as-error case, but that may not have been what the original poster was commenting on.

**Comment by shadowspawn** [comment]
Thanks @cengizhanbasak , I see both your original simple change and second try were consistent with what original poster was asking for. (I had a different case in mind.)

However, there is a work-around, and I don't think this change offers enough to justify the extra parameter to `.outputHelp` for now. 

#997 is one person's issue and has not attracted any likes in a couple of months of being open, and this change would not resolve the couple of previous issues that have mentioned `stderr`. The help related functions are currently a somewhat odd collection of routines that have limited use. I would like a clearer idea of what changes will make them more widely useful and not make one-off additions.

Thank you  for your contributions.

**Pull request closed without merging**
