### PR TITLE
fix option source value

### PR DESCRIPTION
**Pull request by mshima**
# Pull Request

## Problem

'config' option source looks incorrect:
https://github.com/tj/commander.js/blob/82fcb98cc27164a98e0c5f2c6f54621b5bbceef9/lib/command.js#L1618

### CODE REVIEW

**Comment by shadowspawn** [comment]
Yes. 

`config` appears in code as available for author use, although not set by Commander. #1584 #1613

`implied` is set by Commander, but wasn't added to the JSDoc or TSDoc listing the known values. #1724

**Comment by mshima** [comment]
Is there any example on how to use setOptionValueWithSource with 'config'?
Something like this?
```
const options = program.option('--config', 'config.js', 'config.js').parse().opts();
if (options.config) {
  const config = require(options.config);
  for (const [opt, value] of Object.entries(config)) {
    program.setValueWithSource(opt, value, 'config');
  }
}
const updatedOptions = program.opts();
```

**Comment by shadowspawn** [comment]
The use case I had in mind was one of the scenarios in #1584

1) configure program (which includes defaults)
2) read and store config
3) `program.parse()`

**Comment by mshima** [comment]
> The use case I had in mind was one of the scenarios in #1584
> 
> 1. configure program (which includes defaults)
> 2. read and store config
> 3. `program.parse()`

The problem of this workflow is that custom config needs to be parsed manually.
Maybe an event like `on('options:parsed', loadConfigurationFiles)`.

**Comment by shadowspawn** [comment]
A big disadvantage of events is the lack of support for async. The life cycle hooks could be better for something which might include async file handling.

**Pull request closed without merging**
