### PR TITLE
resolves #754 add linter configuration to project

### LINKED ISSUE #754: Add a linter to the project
I'm trying to contribute to this project and I have no idea what code style I'm supposed to be using. And there's nothing to check that I'm doing it right. A linter would make contributing to this project a lot easier.

I also find the use of commas to be rather eclectic, so it would be nice to either enforce that style or use a more standard style.

My proposal is to use [standardJS](https://standardjs.com/) with eslint. It's extremely popular and effective. I've used it for several months now and I hardly ever having to think about it.

I'm happy to set up this tooling.

### PR DESCRIPTION
**Pull request by mojavelinux**
- add linter configuration based on StandardJS
- customize linter to fit with style of project
- update source to reconcile violations

### CODE REVIEW

**Comment by abetomo** [comment]
Thank you!
Could you check it because the test failed?

**Comment by mojavelinux** [comment]
The version of npm that comes with node 4 doesn't honor the lock file, so it wasn't hoisting eslint. We should be upgrading npm to at least npm 3 since npm 2 is deprecated.

**Comment by mojavelinux** [comment]
It was also necessary to move the util.inherits call to the top of the file for node 4. I'm not sure why it gets confused about the order, but it seems to have been fixed in node 6.

**Comment by mojavelinux** [comment]
This exercise as proved how useful the linter actually is ;)

**Comment by mojavelinux** [comment]
Looks like we're going to have to add eslint as a dependency as no version of npm seems to agree on where to put it when it's a transitive dependency ;(

**Comment by mojavelinux** [comment]
I also dropped "node" from the list of node versions to test since it's exactly the same as "9".

**Comment by mojavelinux** [comment]
Finally!

**Comment by abetomo** [comment]
Thank you!

**Comment by vanesyan** [comment]
Thanks!

**Comment by mojavelinux** [comment]
@vanesyan My pleasure.

Shall we reenable that eqeqeq rule?

**Comment by vanesyan** [comment]
Yes, it's definitely a good idea, except that current in some parts of code we rely on poor `null` and `undefined` equality (e.g. `thing == null` -> `thing === undefined || thing === null`), we should be careful in such checks.

**Comment by mojavelinux** [comment]
@vanesyan Fortunately, those are already exceptions in StandardJS, so nothing to worry about.

**Pull request merged**
