### PR TITLE
Support option aliases

### PR DESCRIPTION
**Pull request by ajfranzoia**
Add support for option aliases. References #479.

### CODE REVIEW

**Comment by Turbo87** [comment]
@zhiyelee could you take a look at this proposal and possibly merge it? this seems very useful if you're porting from some other library to `commander` to backwards compat.

**Comment by vanesyan** [comment]
One of the option to make current commander version behave the same way is to define separated option and provide the that to your handler. I think the way you describe things should behave is a bit enormous and should be considered a bad way to design CLI IMHO. @zhiyelee what do you think?

**Comment by shadowspawn** [comment]
This pull request has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by trinhhunganh** [comment]
Please, support this.
thank you!

**Comment by shadowspawn** [comment]
@trinhhunganh 
There was only one 👍 on #479 in over three years and no comments, and only one comment on this Pull Request.

To properly add option aliases would complicate the option parsing and the display of help. (This Pull Request is not a complete proposal.)

> Feel free to open a new issue if it comes up again, with new information and renewed interest.

However if you would like to raise it again, please open a new issue describing what problem you are solving, and optionally how you imagine it might look like in the calling code, and optionally examples of tools that do this. We currently leave unanswered issues open for six months to see how much interest and comments they get.

**Pull request closed without merging**
