### PR TITLE
Rename tsconfig.json to tsconfig.json

### PR DESCRIPTION
**Pull request by angelaschultz0622**
# Pull Request

### CODE REVIEW

**Comment by shadowspawn** [comment]
There is a refactor of the type checking open in #1969. I decided to stick with `tsconfig.json` so more tooling uses it by default. 

What are you trying to do in this PR?

 (Also: #1960 #1962 #1975)

**Review by angelaschultz0622 — COMMENTED** [review]
name change

**Comment by angelaschultz0622** [comment]
Rename

**Comment by shadowspawn** [comment]
You have made a fork of Commander: https://github.com/tj/commander.js

You have made lots of branches on your fork: https://github.com/angelaschultz0622/commander.js/branches

All fine so far. But you are opening Pull Requests to merge your branches into the upstream repository and not your fork. That is spamming this repository and my email with apparently empty pull requests.

If you are experimenting, you should be making a Pull Request against your own fork.

**Pull request closed without merging**
