### PR TITLE
Add override to allow throw instead of process.exit

### PR DESCRIPTION
**Pull request by shadowspawn**
# Pull Request

## Problem

Commander has multiple calls to `process.exit` which is hard to override to use as a library and parse multiple strings, as parsing errors or --help terminate the process. Doing a throw instead would allow appropriate handling and carry on.

Issues: #945 #575 #934 

## Solution

Add `.exitOverride(callback)` routine to do custom handling of code that would otherwise call `process.exit()`. The callback is optional and the default behaviour is to throw an instance of CommanderError which includes the exitCode, a string code, and a message.

This allows writing code like:

```
const program = new commander.Command();
program
  .exitOverride()
  .option(-p, --pepper <type>, 'add pepper');

try {
  program.parse(['node', 'test', '--pepper']);
} catch (err) {
  // custom processing
}
```

(The routine name `exitOverride` is a bit implementation specific rather than friendly, but this is an optional feature and not sure how much or how it will be used.)

### Limitations

- code flow is not changed, so override still expected to throw or exit and not fall through
- executable subcommand calls spawn as async, not currently overriding those `process.exit` as different pattern required
- writing to stdout and stderr as normal before override

## ToDo

- TypeScript
- README
- not doing tests here as have extensive tests in `feature/jest` branch

Making the code visible for discussion and review.

### CODE REVIEW

**Comment by shadowspawn** [comment]
One of the prompts for adding this feature was to simplify writing unit tests. The test file for exitOverride itself (on a different branch) is: 

https://github.com/shadowspawn/commander.js/blob/feature/jest/tests-jest/command.exitOverride.test.js

**Comment by shadowspawn** [comment]
Added support for async calls in executableSubcommand.

**Comment by shadowspawn** [comment]
Allows custom exit codes: #188 #436

**Comment by shadowspawn** [comment]
The implementation already landed in the Jest PR. This PR now effectively promotes it from private `_exitOverride` to public `exitOverride`.

Added description to README.

Suggested line for CHANGELOG:

* `.exitOverride()` allows override of calls to `process.exit` for additional error handling and to keep program running ([#1040])

**Comment by LXSMNSYC** [comment]
Hello, I was looking for a solution to prevent "--help" from exiting the CLI.

I tried using `exitOverride`, but it doesn't really prevent it from exiting. Is there any way for this?

**Comment by shadowspawn** [comment]
@LXSMNSYC 
`exitOverride` would be my suggestion. Open a new issue with some more details. (I am not sure what you mean by "doesn't really prevent it from exiting".)

**Comment by LXSMNSYC** [comment]
> @LXSMNSYC
> `exitOverride` would be my suggestion. Open a new issue with some more details. (I am not sure what you mean by "doesn't really prevent it from exiting".)

I have found a work around to my solution.

I have to take a look at commander's index js to know how it executes commands, and ti understand the behavior in general :)

**Pull request merged**
