### PR TITLE
Fix help section order and padding

### LINKED ISSUE #500: Display description and options before subcommands
See:
https://github.com/tj/commander.js/blob/master/index.js#L1004-L1008

The global description and options are shown _after_ the subcommands list.

### PR DESCRIPTION
**Pull request by ValentinTrinque**
Fixes #500

### CODE REVIEW

**Comment by ValentinTrinque** [comment]
Ping @abetomo

**Comment by abetomo** [comment]
@ValentinTrinque Thank you!

**Comment by ValentinTrinque** [comment]
Thank you for your reactivity :)

**Comment by abetomo** [comment]
@vanesyan Please review.

**Comment by vanesyan** [comment]
Shouldn't commands come first and options after em' (imho, I don't really convenient way)? Otherwise looks good to me

**Comment by ValentinTrinque** [comment]
I've used Git man pages as an example for the ordering. Also, in my opinion, the options applies directly to the executable such as verbosity, or any option to _configure_ the execution. Then, the commands have arguments which can be expressed as plain word `list`, `delete` or as _option-like_ style `-l`, `-d` respectively.

Some may say that is a matter of style / taste, but it _makes sense_ to me. Also, since git sees it this way as well, it should make us confident about this changes.

**Comment by vanesyan** [comment]
Makes sens

**Comment by vanesyan** [comment]
LGTM that way

**Pull request merged**
