### PR TITLE
move output information to printer

### PR DESCRIPTION
**Pull request by cravler**
```js
const { Command, Printer } = require('commander');

class CustomPrinter extends Printer {
 
    error(msg, ...args) {
        super.error(this.format(msg), ...args);
    }
 
    outputHelp(program) {
        return this.format(super.outputHelp(program));
    }
 
    format(str) {
        return [
            '\n', str.replace(/^/gm, '  '), '\n'
        ].join('');
    }
 
}

const program = new Command('example', new CustomPrinter());

program.version('0.0.1')
    .command('setup [env]')
    .description('application simple description', {
        env: 'env value'
    })
    .option('-f, --foo', 'enable some foo')
    .action(function(env, options) {});

program.parse(process.argv);
if (!program.args.length) program.help();
```

### CODE REVIEW

**Comment by cravler** [comment]
any comments?

**Comment by cravler** [comment]
Is this repository supported?

**Comment by shadowspawn** [comment]
@cravler 
What problem are you solving with this Pull Request? 
Are there open Issues that this will resolve?

Or is this primarily an object separation suggestion, rather than a functional suggestion?

**Comment by cravler** [comment]
This separation adds ability to write custom printers without touching the default. In my case I have `Colorized Printer`

**Comment by shadowspawn** [comment]
Thanks @cravler. This is quite interesting, but changes a lot of code. Offering customisation by inheritance is also more challenging for future maintenance than a callback.

I don't wish to add this at the moment. However we have a variety of requests around help and output. This may get revisited in the future if it can be used to resolve more issues.

Thank you for your contributions.

**Pull request closed without merging**
