### PR TITLE
Fixed #37, --help should not display first

### LINKED ISSUE #37: --help should not display first
ex:

```

Usage: log [options]

Options:

  -h, --help         output usage information
  -V, --version      output the version number
  -a, --addr <addr>  bind to the given address
```

### PR DESCRIPTION
**Pull request by vicjohnson1213**
Although the original suggestion was from 2011, the issue is still open.  So if this issue is still relevant here is a pull request to move the `--help` option to the end.

### CODE REVIEW

**Comment by abetomo** [comment]
@vicjohnson1213 Would you please resolve the conflict?

**Comment by vicjohnson1213** [comment]
Sure! haha didn't expect this to go anywhere after nearly 2 years ;)

**Comment by abetomo** [comment]
Thank you!
I became a Collaborator recently, so I am checking the accumulated PR!

**Comment by vanesyan** [comment]
Seems good to me

**Comment by vanesyan** [comment]
Can you please resolve conflict on top of master branch

**Pull request merged**
