### PR TITLE
Add `"types"` to `"exports"`

### LINKED ISSUE #1703: Be able to import types when using `NodeNext` TypeScript module resolution
I'm making an npm package which uses `ora`. To use `ora`, I switched to `NodeNext` module resolution. After doing that, the type checking for `commander` stopped working. I think `package.json` needs to be updated to be compatible with `NodeNext` module resolution. 

Here is the guide to by the author of `ora`: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c.
Here is some related TypeScript documentation: https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#esm-nodejs

### PR DESCRIPTION
**Pull request by ChocolateLoverRaj**
# Pull Request

## Problem
Fixes #1703 

## Solution
Add `"types"` to `"exports"`

### CODE REVIEW

**Review by shadowspawn — CHANGES_REQUESTED** [review]
Thanks. The example on this page: https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing

has a comment saying "types" must come first:

```
            // Entry-point for TypeScript resolution - must occur first!
            "types": "./types/index.d.ts",
```

(It did work for me last when I was experimenting, but I think we better follow the example.)

**Comment by shadowspawn** [comment]
This PR is to work with a _future_ version of TypeScript. I have been doing a lot of reading to try and understand whether it is safe for us to ship now. And still not sure! Maybe I should ask...

1) The "types" value in "exports" is described in the Node.js 16 documentation so that part at least appears in something released.
https://nodejs.org/dist/latest-v16.x/docs/api/packages.html#community-conditions-definitions

2) I found these comments in long threads, two talking about updates by library authors:
- https://github.com/microsoft/TypeScript/issues/46452#issuecomment-1031713598
- https://github.com/microsoft/TypeScript/issues/46452#issuecomment-1031961407
- https://github.com/microsoft/TypeScript/issues/46334#issuecomment-943632787

Some interesting information about emit vs resolving with answer from an expert:
- https://stackoverflow.com/questions/71463698/why-we-need-nodenext-typescript-compiler-option-when-we-have-esnext

3) `rxjs` have merged a PR doing this just recently, and also wondering whether to go before TypeScript supports it!

- https://github.com/ReactiveX/rxjs/pull/6802

**Comment by shadowspawn** [comment]
Asked if stable enough for release: https://github.com/microsoft/TypeScript/issues/46452#issuecomment-1070369344

**Comment by shadowspawn** [comment]
And got a "100% yes".

https://github.com/microsoft/TypeScript/issues/46452#issuecomment-1070377450

**Comment by shadowspawn** [comment]
Oh, but then there was a followup. I need to reread some of the earlier comments again!

https://github.com/microsoft/TypeScript/issues/46452#issuecomment-1070418207

**Comment by ChocolateLoverRaj** [comment]
@shadowspawn How could adding a `"types"` entry in `"exports"` break things?

**Comment by shadowspawn** [comment]
> How could adding a `"types"` entry in `"exports"` break things?

In general, by making the behaviour worse for a use case where something reads `"exports"` and recognises the `"types"` entry. Not just TypeScript, say ts-node or WebStorm. (Hypothetical examples, I have not idea what the do with `"exports"`!)

**Comment by shadowspawn** [comment]
@abetomo I am going to test now one more time with `typescript@next` generating CommonJS and ESM, then call it good. Could make it into v9.1, but no worries if it misses.

**Review by shadowspawn — APPROVED** [review]
LGTM

**Review by abetomo — APPROVED** [review]
👍

**Comment by abetomo** [comment]
I think it is fine to release it next time.

**Comment by shadowspawn** [comment]
Ok. I won't merge until after release we have lined up.

**Pull request merged**
