### PR TITLE
Data overload

### PR DESCRIPTION
**Pull request by ericuldall**
New features allow the following:

```
#!/usr/bin/env node
var program = require('commander');

program
  .version('0.0.1')
  .description('Test')
  .usage('[options] string')
  .option('-t, --type [value]', 'Type')
  .option('-f, --format', 'Format')
  .parse(process.argv);

var type = program.get('type'); //if exists return type, else returns false
var options = program.get(); //return all options, or empty object

var has = program.has('type', function(type){
    console.log(type); //will return if type exists
});
console.log(has); //boolean

var has_all = program.has_all(['type', 'format'], function(type, format){
    console.log(type, format); //will return if both exist
});
console.log(has_all); //boolean

}
```

### CODE REVIEW

**Comment by zhiyelee** [comment]
hold on this.  New added `get` `has` will overwrite custom command with same name. https://github.com/tj/commander.js/issues/404

**Comment by ericuldall** [comment]
So commands will have to be moved out of the objects main scope as well, for this to be viable?

**Comment by ericuldall** [comment]
UPDATE: I'm not seeing any conflict with custom commands. Can you provide an example of this case?

**Comment by ericuldall** [comment]
I've tested this with the following scenario:

cmd: mycmd
subcmd: mycmd-get
```
mycmd get -y
```
works as expected. Am I missing something?

**Comment by zhiyelee** [comment]
oh, sorry, it's about options. 
> Just want to give some feedback here to help others avoid a little pitfall: you cannot use --once as an argument, probably because the name collides with some internals of commander. Interestingly, the once argument will revert the expected behavior: myprog --once will set commander.once=undefined, so a falsy value, while running myprog will set it to a function as expected. 

I don't want to introduce more these cases until we fix this issue.

**Comment by ericuldall** [comment]
I think my pull request fixes that issue.

**Comment by shadowspawn** [comment]
I am still investigating options. For now, I'll note that `get()` and `has()` are similar in name and purpose to the new `Map`object, and should probably behave in similar way.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

**Comment by shadowspawn** [comment]
I am closing this in favour of #951, which builds on work in this Pull Request and aims for backwards compatibility.
 
Thank you  for your contributions.

**Comment by shadowspawn** [comment]
I have opened a new Pull Request which allows storing option values separately rather than as command properties (access using .opts()), and passes the options (rather than the command) to the action handler. Opt-in using

```
program.configureCommand({ modern: true });
```

See #1102

**Pull request closed without merging**
