### PR TITLE
ability to specify `minColumnWidth` for `Help.wrap`

### PR DESCRIPTION
**Pull request by cravler**
# Pull Request

### CODE REVIEW

**Comment by shadowspawn** [comment]
Do you have a situation when you want to be able to change minColumnWidth? Or suggesting it because it is currently a hard-coded value in the code?

For historical interest, this was actually a parameter in the original PR! I removed it rather than try and add documentation for the parameter, as I struggled to differentiate it from the "width" parameter. The current variable name is the best I came up with at the time.

**Comment by cravler** [comment]
yes, i want set it to `minColumnWidth=0`, so it would be totally disabled

i played with different terminal sizes and app looks better when it disabled

`minColumnWidth=0`:
image

`minColumnWidth=40`
image

**Comment by cravler** [comment]
maybe better to make like this?

```js
class Help {
    formatHelp(cmd, helper) {
        //...

        function wrap(str, width, indent) {
            // Do not wrap if not enough room for a wrapped column of text (as could end up with a word per line).
            const columnWidth = width - indent;
            const minColumnWidth = 40;
            if (columnWidth < minColumnWidth) return str;
            return return helper.wrap(str, width, indent);
        }

        function formatItem(term, description) {
          if (description) {
            const fullText = `${term.padEnd(termWidth + itemSeparatorWidth)}${description}`;
            return wrap(fullText, helpWidth - itemIndentWidth, termWidth + itemSeparatorWidth);
          }
          return term;
        };

        // ...
    }
}
```

**Comment by shadowspawn** [comment]
The reason for skipping the wrap at small sizes is that in the worst case can get a word per line, and unlike the fallback unwrapped output, this does not reflow as the terminal window is made wider as it is hard wrapped. e.g.

```
  daemon              Daemon
                      to
                      listen
                      to
                      multiple
                      sockets
                      connections
  init [name] [path]  Created
                      a new
                      application
```

But being able to configure the cut-off is a reasonable request. Still thinking about that.

**Comment by shadowspawn** [comment]
I do not think this will be be used much, but it isn't a front-facing routine and this hopefully makes it more usable for some custom overrides. Ok.

If you are still keen add the TypeScript, and I'll add some comments when I merge it if it passes review.

**Review by shadowspawn — APPROVED** [review]
LGTM. I'll add an explanation of the new parameter.

**Review by abetomo — APPROVED** [review]
👍

**Pull request merged**
